// PROMISE - ASSINCRONA
// SETTIMEOUT
// CALLBACKS
// NODE JS
// PACOTE DE CORES - CHALK
// FETCH - XMLHttpRequest
// NPM - GERENCIADOR DE PACOTES - INSTALAR E DESINSTALAR PACOTES 
// PAKCAGE.JSON - JSON
// NODE EXPRESS
// GET - MÉTODO BUSCA

console.log("kassiane")